method: bayes

metric:
  name: test/mse
  goal: minimize

parameters:
  batch_size:
    values: [2, 4, 8, 16, 32, 64, 128]

  num_epochs:
    values: [5, 10, 15, 20]

  learning_rate:
    distribution: log_uniform_values
    min: 1e-6
    max: 1e-2

  weight_decay:
    distribution: log_uniform_values
    min: 1e-4
    max: 1e-1

  gradient_accumulation_steps:
    values: [1, 2, 4, 8]
