method: bayes

metric:
  name: test/mse
  goal: minimize

parameters:
  num_fusion_layers:
    value: 2

  fusion_hidden_dim:
    distribution: int_uniform
    min: 256
    max: 2048

  batch_size:
    values: [4, 8, 16, 32]

  num_epochs:
    values: [5, 10, 15, 20]

  learning_rate:
    distribution: log_uniform_values
    min: 1e-5
    max: 1e-3

  weight_decay:
    distribution: log_uniform_values
    min: 1e-4
    max: 1e-1

  gradient_accumulation_steps:
    values: [1, 2, 4, 8]
